name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  meta: ^1.3.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.3
dev_dependencies:
  lints: ^1.0.1
